Update python versions in travis (#70)
* Update flake8 to 3.7.9 in requirements-dev

flake8 version 3.3.0 does not support python 3.8, and will yield the
following error:

    ... SNIP ...
      File
    "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/pyflakes/checker.py",
    line 862, in handleNode

        handler = self.getNodeHandler(node.__class__)

      File
    "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/pyflakes/checker.py",
    line 696, in getNodeHandler

        self._nodeHandlers[node_class] = handler = getattr(self, nodeType)

    AttributeError: 'FlakesChecker' object has no attribute 'CONSTANT'

* Update python versions in travis

Python 3.7 has been released, so replace 3.7-dev with 3.7. 3.8 is
stable.